### PR TITLE
Import Schema classes and tests from Garden framework

### LINKED ISSUE #4702: Copy relevant schema classes and tests from the garden repo
The garden repo has the appropriate Schema object and unit tests for it. There is also the ValidationException class that might depend on other classes.

Copy the classes and unit tests over and get them passing. All project classes should stay in their same namespaces, but it might make sense to re-namespace the unit tests.

Hint: Look at the epic for some general schema guidelines.

### PR DESCRIPTION
**Pull request by initvector**
This update grabs [`Schema`](https://github.com/vanilla/garden/blob/6b771702fbfdc8070211a4c4b7ea257f3e6e060b/src/Schema.php), along with its tests and dependencies, from the [Garden framework repo](https://github.com/vanilla/garden).

Closes  #4702

### CODE REVIEW

File: library/Garden/Exception/ValidationException.php [hunk 1]
```diff
@@ -0,0 +1,53 @@
...
+
+use Garden\Validation;
+
+/**
+ * An exception that was built from a {@link Validation} object.
+ *
+ * The validation object collects errors and is mutable. Once it's ready to be thrown as an exception it gets converted
+ * to an instance of the immutable {@link ValidationException} class.
+ */
+class ValidationException extends ClientException {
```
Comment (tburry) [inline library/Garden/Exception/ValidationException.php]: Oh shoot. Did not realize this would bring in the ClientException which I don't think I'm ready for. Can you refactor this to just extend \Exception for now and then remove ClientException and Response?

File: library/core/functions.general.php [hunk 2]
```diff
@@ -214,6 +214,26 @@ function arrayValueI($Needle, $Haystack, $Default = false) {
...
+    /**
+     * Select the first non-empty value from an array.
+     *
+     * @param array $keys An array of keys to try.
+     * @param array $array The array to select from.
+     * @param mixed $default The default value if non of the keys exist.
+     * @return mixed Returns the first non-empty value of {@link $default} if none are found.
+     * @category Array Functions
+     */
+    function array_select(array $keys, array $array, $default = null) {
```
Comment (tburry) [inline library/core/functions.general.php]: camelCase this one if it's still required.

File: library/core/functions.general.php [hunk 3]
```diff
@@ -3859,6 +3879,37 @@ function slugify($text) {
...
+     * Returns whether or not a string ends with another string.
+     *
+     * This function is not case-sensitive.
+     *
+     * @param string $haystack The string to test.
+     * @param string $needle The substring to test against.
+     * @return bool Whether or not `$string` ends with `$with`.
+     * @category String Functions
+     */
+    function str_ends($haystack, $needle) {
```
Comment (tburry) [inline library/core/functions.general.php]: camelCase

File: library/core/functions.general.php [hunk 4]
```diff
@@ -214,6 +214,26 @@ function arrayValueI($Needle, $Haystack, $Default = false) {
...
+    /**
+     * Select the first non-empty value from an array.
+     *
+     * @param array $keys An array of keys to try.
+     * @param array $array The array to select from.
+     * @param mixed $default The default value if non of the keys exist.
+     * @return mixed Returns the first non-empty value of {@link $default} if none are found.
+     * @category Array Functions
+     */
+    function arraySelect(array $keys, array $array, $default = null) {
```
Comment (tburry) [inline library/core/functions.general.php]: Sorry about this, but can we make this a private method of Schema instead? I want to reduce dependencies as much as possible.

File: library/core/functions.general.php [hunk 5]
```diff
@@ -3859,6 +3879,37 @@ function slugify($text) {
...
+     * Returns whether or not a string ends with another string.
+     *
+     * This function is not case-sensitive.
+     *
+     * @param string $haystack The string to test.
+     * @param string $needle The substring to test against.
+     * @return bool Whether or not `$string` ends with `$with`.
+     * @category String Functions
+     */
+    function strEnds($haystack, $needle) {
```
Comment (tburry) [inline library/core/functions.general.php]: Sorry about this, but can we make this a private method of Schema instead? I want to reduce dependencies as much as possible.
