### PR TITLE
Fix untranslatable strings in ban.php

### LINKED ISSUE #1723: Make view ban.php translatable
The contents of / applications / dashboard / views / settings / ban.php file not ready for localization.
Please fix it.

### PR DESCRIPTION
**Pull request by bleistivt**
fixes #1723

### CODE REVIEW

File: applications/dashboard/views/settings/ban.php [hunk 1]
```diff
@@ -17,14 +17,14 @@
             echo $this->Form->label('Value or Pattern', 'BanValue');
             echo $this->Form->textBox('BanValue');
             ?>
-            <span>Use asterisks for wildcards, e.g. &lsquo;*@hotmail.com&rsquo;</span>
+            <span><?php echo t('Use asterisks for wildcards, e.g. &lsquo;*@hotmail.com&rsquo;'); ?></span>
```
Comment (tburry) [inline applications/dashboard/views/settings/ban.php]: `t('Use asterisks for wildcards', 'Use asterisks for wildcards, e.g. &lsquo;*@hotmail.com&rsquo;')`
