### PR TITLE
Add boilerplate/keystone theming styles fixes

### LINKED ISSUE #8472: Keystone: Category Following feature 'Follow' icon has disappeared  with Hero Image enabled
I noticed this on my demo site.

Steps to reproduce:
- Enable Keystone
- Enable Hero Image plugin
- Go to Keystone Theme options and enable hero image banner or hero image with searchbox

the 'Follow/Following' icons that appear within Discussion type categories when the Category Following feature is enable are not visible.

Missing:
screen shot 2019-03-01 at 10 05 12 am

Present when hero image plug related options are disabled:
screen shot 2019-03-01 at 10 23 37 am

@igraziatto

### LINKED ISSUE #8483: Keystone: Mobile Mebox icons wrong alignment on Profile Page
On Keystone/theme-boilerplate, icons on mobile Mebox navigation align to the left when user is on Profile Page:

  | Wrong: | Right: |
  | ------ | ------ |
  |    screen shot 2019-03-04 at 3 39 37 pm    |    screen shot 2019-03-04 at 3 41 57 pm    |

### LINKED ISSUE #8501: Keystone: icon too big
Hey Isis, the "heart icon" is too big in the circle. 
Please see the image below:
screen shot 2019-03-07 at 1 40 06 pm

Would be good to have 1px of padding each side. 

If you have any question, let me know.

### LINKED ISSUE #8567: Keystone: Point Score should not show (display: none ignored)
**Describe the bug**
The points show  up on the list view, and should not, especially if no gamification feature enabled.

**To Reproduce**
1. Enable Keystone

**Expected behavior**
Should not see points.

**Screenshots**
image

**Additional context**
@igraziatto agreed it may be an issue where hidden is ignored and suggested apply `display:none`  to 
`.MessageList .MItem.DiscussionScore`

### LINKED ISSUE #8610: Keystone - Search Bar Disappears
**Describe the bug**
Search bar disappears when screen width is from 770 - 994px.
By the default the search lives on the top of the top of the side panel. As such it disappears when the side panel hides. It reappears at the top across the width of the page.

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using?
Core Vanilla
2. Did you follow our generic troubleshooting steps already?
3. What Vanilla version are you using?
4. When did the issue start?

**To Reproduce**
1. Reduce the width of the window to between 770 - 994px and you'll notice it disspears.

**Expected behavior**
Would be nice if the wider search appears right away.

**Screenshots**
image

image

**Additional context**

### LINKED ISSUE #8731: ProfilePhoto in Mebox changes when you're on an another user profile page
The Profile Photo of your user changes when you're going on an another user profile page to his Profile Photo. 

Screen-Shot-2019-04-25-at-10 12 28-AM

### LINKED ISSUE #8741: Theme Boilerplate/Keystone MeBox counts are not aligned properly
**Describe the bug**
The count icons in the UserDropdown are not aligned properly.

**Vanilla info**
1. Are you sure this is a core Vanilla problem and not caused by any addon you are using?
2. Did you follow our generic troubleshooting steps already?
3. What Vanilla version are you using?
4. When did the issue start?

**To Reproduce**
1. Do some actions to get counts in the MeBox. It's probably easy to just get a few items in the spam queue.
2. Open the MeBox.
3. Notice the misalignement

**Expected behavior**

**Screenshots**

|Actual|Expected|
|---|---|
|image|image|

### PR DESCRIPTION
**Pull request by igraziatto**
closes #8741
closes #8483
closes #8501
closes #8567
closes #8610 
closes #8472
closes #8731

### CODE REVIEW

File: library/SmartyPlugins/function.follow_button.php [hunk 1]
```diff
@@ -0,0 +1,28 @@
...
+
+/**
+ * Follow button.
+ *
+ * @return string
+ */
+function smarty_function_follow_button() {
+    $followButton = '';
+    $controller = Gdn::controller();
+    $controller->fetchViewLocation('helper_functions', 'categories', false, false);
```
Comment (charrondev) [inline library/SmartyPlugins/function.follow_button.php]: I see you've fetched the view location but are not including it. The function happens to be included from somewhere else but that may not always be the case. Be sure to do a `require_once` of the actual view location.

File: themes/keystone/views/default.master.tpl [hunk 2]
```diff
@@ -90,7 +92,9 @@
                                 </div>
                                 {if $User.SignedIn}
                                     <button class="mobileMeBox-button">
-                                        {module name="UserPhotoModule"}
+                                        <span class="Photo PhotoWrap">
+                                            <img src="{$User.Photo}" class="ProfilePhotoSmall" alt="{t c='Avatar'}">
```
Comment (charrondev) [inline themes/keystone/views/default.master.tpl]: Is this user photo src being sanitized? Looks like an XSS to me.

File: themes/theme-boilerplate/views/partials/header.tpl [hunk 3]
```diff
@@ -31,7 +31,9 @@
                 </div>
                 {if $User.SignedIn}
                     <button class="mobileMeBox-button">
-                        {module name="UserPhotoModule"}
+                        <span class="Photo PhotoWrap">
+                            <img src="{$User.Photo}" class="ProfilePhotoSmall" alt="{t c='Avatar'}">
```
Comment (charrondev) [inline themes/theme-boilerplate/views/partials/header.tpl]: Looks like an XSS here. Please make sure the src is escaped.

**Comment by charrondev** [comment]
I still see the incorrect user photo on the profile page.

image

---

It looks my page title is duplicated with category following now:

image
